export const ADD_FAVORITE_CITY = "ADD_FAVORITE_CITY";
export const REMOVE_FAVORITE_CITY = "REMOVE_FAVORITE_CITY";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_DEGREES = "TOGGLE_DEGREES";
